### ISSUE TITLE
prob with awpl_rounds_pause_num

### ISSUE THREAD

**Issue by fred0r** [Nord1cWarr1or/AWP-Limiter#12]
seems when `awpl_rounds_pause_num` is configured, that a player is blocked from buying awp - regardless if he didnt buy one during rounds inbetween,while no one else bought a awp in the particular team.
thought that this option 'only' prevents ppl from buying the awp in **EVERY** `awpl_rounds_pause_num` in a row. 
would be great if the `awpl_rounds_pause_num`-check gets reset when the player lost his awp and doesnt buy a new one in the 'nextround'.

**Comment by Nord1cWarr1or** [comment]
I don't get it.
This setting is made so that one player can not take AWP several times in a row. After taking an AWP, he must wait N rounds to take it again.

**Comment by fred0r** [comment]
ehem - i misunderstood that option - thx.
